package modelos;

import java.util.List;

import general.ManejarEntidades;

// Generated 23/05/2016 01:08:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * Anuncios generated by hbm2java
 */
public class Anuncios extends ManejarEntidades implements java.io.Serializable {

	private int id;
	private Contactos contactos;
	private Integer numero;
	private String anuncio;	
	private String estatus;

	public Anuncios() {
	}

	public Anuncios(int id) {
		this.id = id;
	}

	public Anuncios(int id, Contactos contactos, Integer numero,
			String anuncio, String estatus) {
		this.id = id;
		this.contactos = contactos;
		this.numero = numero;
		this.anuncio = anuncio;	
		this.estatus = estatus;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Contactos getContactos() {
		return this.contactos;
	}

	public void setContactos(Contactos contactos) {
		this.contactos = contactos;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getAnuncio() {
		return this.anuncio;
	}

	public void setAnuncio(String anuncio) {
		this.anuncio = anuncio;
	}

	public String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(String estatus) {
		this.estatus = estatus;
	}
	
	public List <Object[]> CargarLista(Integer id) throws Exception{
		List <Object[]> lista = null;
		try{		
		String sql = "select a.id, a.numero, a.anuncio, a.estatus from Anuncios a where a.contactos.id = "+id+" order by 2";
		lista = (List<Object[]>) ConsultarLista(sql);
		}catch (Exception ex) {
			System.out.println("Cargar Lista Anuncios por Contacto: "+ex.getMessage());			
		}
		
		return lista;
	}
	
	public List <Object[]> CargarListaTipo(String where) throws Exception{
		List <Object[]> lista = null;
		try{		
		String sql = "select a.numero, a.contactos.direccion, a.anuncio from Anuncios a where "+where+" and a.contactos.estatus = 'AC' and a.estatus= 'AC' order by 1";
		lista = (List<Object[]>) ConsultarLista(sql);
		}catch (Exception ex) {
			System.out.println("Cargar Lista Anuncios por Tipo: "+ex.getMessage());			
		}
		
		return lista;
	}
	
	public List<Object[]> ConsultarAnuncio(Integer id){
		List <Object[]> lista = null;
		try{		
			String sql = "select a.id, a.numero, a.anuncio, a.estatus " +
					"from Anuncios a where a.id= "+id+"";
			lista = (List<Object[]>) Consultar(sql);
			}catch (Exception ex) {
				System.out.println("ConsultarAnuncio: "+ex.getMessage());			
			}
		return lista;
	}

	
	
}
