package modelos;

import general.ManejarEntidades;

import java.util.List;

// Generated 23/05/2016 01:08:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * Root generated by hbm2java
 */
public class Root extends ManejarEntidades implements java.io.Serializable {

	private int id;
	private String usuario;
	private String clave;

	public Root() {
	}

	public Root(int id) {
		this.id = id;
	}

	public Root(int id, String usuario, String clave) {
		this.id = id;
		this.usuario = usuario;
		this.clave = clave;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}
	
	public List<Object[]> ConsultarRoot(String cusuario) {
		List<Object[]> objeto = null;
		try {				
				   String Sql ="select a.id, a.usuario, a.clave ";
				   Sql = Sql + "from Root a ";
				   Sql = Sql + "where a.usuario ='"+cusuario+"' ";
				   
			objeto = this.Consultar(Sql);
		} catch (Exception ex) {
			System.out.println("ConsultarRoot: "+ex.getMessage());			
		}
		return objeto;
	}


}
